---

name: shellcheck

on:
  pull_request:
    paths:
      - .github/workflows/shellcheck.yml
      - '**.sh'
  push:
    paths:
      - .github/workflows/shellcheck.yml
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v5
      -
        run: find . -type f -name "*.sh" -exec shellcheck {} +

...
